<a href="https://colab.research.google.com/github/Nikhil14091997/ML-Short-projects/blob/main/Breast%20Cancer%20Classification%20-%20SVM/Breast_Cancer_classification_SVM_Optimized.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
df_cancer = pd.DataFrame(np.c_[cancer['data'], cancer['target']], columns = np.append(cancer['feature_names'], ['target']))
df_cancer.tail()

mean radius  mean texture  ...  worst fractal dimension  target
564        21.56         22.39  ...                  0.07115     0.0
565        20.13         28.25  ...                  0.06637     0.0
566        16.60         28.08  ...                  0.07820     0.0
567        20.60         29.33  ...                  0.12400     0.0
568         7.76         24.54  ...                  0.07039     1.0

[5 rows x 31 columns]

In [4]:
df_cancer.head()

mean radius  mean texture  ...  worst fractal dimension  target
0        17.99         10.38  ...                  0.11890     0.0
1        20.57         17.77  ...                  0.08902     0.0
2        19.69         21.25  ...                  0.08758     0.0
3        11.42         20.38  ...                  0.17300     0.0
4        20.29         14.34  ...                  0.07678     0.0

[5 rows x 31 columns]

In [5]:
from sklearn.model_selection import train_test_split
X = df_cancer.drop(['target'], axis = 1)
y = df_cancer['target']


In [7]:
X

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [6]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
564    0.0
565    0.0
566    0.0
567    0.0
568    1.0
Name: target, Length: 569, dtype: float64

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
X_train

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
338       10.050         17.53  ...          0.2894                  0.07664
427       10.800         21.98  ...          0.2965                  0.07662
406       16.140         14.86  ...          0.2778                  0.07012
96        12.180         17.84  ...          0.2227                  0.07376
490       12.250         22.44  ...          0.3100                  0.08203
..           ...           ...  ...             ...                      ...
277       18.810         19.98  ...          0.2567                  0.05737
9         12.460         24.04  ...          0.4366                  0.20750
359        9.436         18.32  ...          0.2454                  0.08136
192        9.720         18.22  ...          0.1909                  0.06559
559       11.510         23.93  ...          0.2112                  0.08732

[455 rows x 30 columns]

In [12]:
X_test

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
512        13.40         20.52  ...          0.3585                  0.11090
457        13.21         25.25  ...          0.2444                  0.06788
439        14.02         15.66  ...          0.2136                  0.06710
298        14.26         18.17  ...          0.2636                  0.07676
37         13.03         18.42  ...          0.1987                  0.06169
..           ...           ...  ...             ...                      ...
213        17.42         25.56  ...          0.1603                  0.06818
519        12.75         16.70  ...          0.3071                  0.08557
432        20.18         19.54  ...          0.3032                  0.08075
516        18.31         20.58  ...          0.3074                  0.07863
500        15.04         16.74  ...          0.2177                  0.08549

[114 rows x 30 columns]

In [13]:
y_train

338    1.0
427    1.0
406    1.0
96     1.0
490    1.0
      ... 
277    0.0
9      0.0
359    1.0
192    1.0
559    1.0
Name: target, Length: 455, dtype: float64

In [18]:
y_test
y_test.shape


(114,)

In [19]:
X_train_min = X_train.min()
X_train_max = X_train.max()
X_train_range = (X_train_max - X_train_min)
X_train_scaled = (X_train - X_train_min)/X_train_range
X_train.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
338        10.05         17.53  ...          0.2894                  0.07664
427        10.80         21.98  ...          0.2965                  0.07662
406        16.14         14.86  ...          0.2778                  0.07012
96         12.18         17.84  ...          0.2227                  0.07376
490        12.25         22.44  ...          0.3100                  0.08203

[5 rows x 30 columns]

In [20]:
X_train_scaled.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
338     0.145251      0.324481  ...        0.261975                 0.141677
427     0.180747      0.509129  ...        0.275971                 0.141545
406     0.433480      0.213693  ...        0.239109                 0.098911
96      0.246060      0.337344  ...        0.130495                 0.122786
490     0.249373      0.528216  ...        0.302582                 0.177030

[5 rows x 30 columns]

In [21]:
X_test_min = X_test.min()
X_test_max = X_test.max()
X_test_range = (X_test_max - X_test_min)
X_test_scaled = (X_test - X_test_min)/X_test_range
print(X_test.head())

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
512        13.40         20.52  ...          0.3585                  0.11090
457        13.21         25.25  ...          0.2444                  0.06788
439        14.02         15.66  ...          0.2136                  0.06710
298        14.26         18.17  ...          0.2636                  0.07676
37         13.03         18.42  ...          0.1987                  0.06169

[5 rows x 30 columns]


In [22]:
print(X_test_scaled.head())

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
512     0.390001      0.338738  ...        0.516549                 0.618709
457     0.376934      0.505464  ...        0.219182                 0.109295
439     0.432639      0.167430  ...        0.138911                 0.100059
298     0.449144      0.255904  ...        0.269221                 0.214446
37      0.364555      0.264716  ...        0.100078                 0.035998

[5 rows x 30 columns]


In [26]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
svc_model_1 = SVC()
svc_model_1.fit(X_train, y_train)
y_pred_1 = svc_model_1.predict(X_test)
cm_1 = confusion_matrix(y_test, y_pred_1)
print(np.array(cm_1))
accuracy_score(y_test, y_pred_1)
#print(classification_report((y_test, y_pred_1))

[[40  7]
 [ 1 66]]


0.9298245614035088

In [27]:
svc_model_2 = SVC()
svc_model_2.fit(X_train_scaled, y_train)
y_pred_2 = svc_model_2.predict(X_test_scaled)
cm_2 = confusion_matrix(y_test, y_pred_2)
print(np.array(cm_2))
accuracy_score(y_test, y_pred_2)

[[47  0]
 [ 8 59]]


0.9298245614035088

In [33]:
param_grid= {'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 'kernel': ['rbf']}
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)
# fitting the model for grid search
grid.fit(X_train_scaled, y_train)


Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.901, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.978, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.934, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.956, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.989, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.901, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV] ...... C=0.1, gamma=0.001, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=0.1, gamma=0.001, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=0.1, gamma=0.001, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=0.1, gamma=0.001, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=0.1, gamma=0.001, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=0.0001, kernel=rbf .................................
[CV] ..... C=0.1, gamma=0.0001, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=0.0001, kernel=rbf .................................
[CV] ..... C=0.1, gamma=0.0001, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=0.0001, kernel=rbf .................................
[CV] .

[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed:    1.3s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [34]:
# print best parameter after tuning
print("Printing Best Parameters: \n", grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

Printing Best Parameters: 
 {'C': 1, 'gamma': 1, 'kernel': 'rbf'}
SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)


In [35]:

grid_predictions = grid.predict(X_test_scaled)
cm_3 = confusion_matrix(y_test, grid_predictions)
print(np.array(cm_3))
accuracy_score(y_test, grid_predictions)

[[47  0]
 [ 8 59]]


0.9298245614035088